# coding=utf-8
from ExoiTest.CompareExoi.AbstractEXOI import AbstractEXOI
from lxml import etree
import time


class EXOIFinancialStatements(AbstractEXOI):

    def __init__(self):
        AbstractEXOI.__init__(self)

        self.IncomeStatement_mapping = {
            20191: 'NetIncomeContinuousOperationsNetMinorityInterest',
            20192: 'AccretionOnPreferredStock',
            20193: 'AccruedPreferredStockDividends',
            20194: 'AcquiredInProcessRnD',
            20195: 'AcquisitionExpense',
            20196: 'AdministrativeExpense',
            20197: 'AgencyFees',
            20198: 'AgencyFeesAndCommissions',
            20199: 'AllowancesForConstruction',
            20007: 'Amortization',
            20008: 'SecuritiesAmortization',
            20200: 'CapitalnBusinessTaxes',
            20201: 'CededPremiums',
            20202: 'CommissionExpenses',
            20203: 'CommissionRevenue',
            20013: 'CostOfRevenue',
            20204: 'CreditCard',
            20016: 'CumulativeEffectOfAccountingChange',
            20017: 'Depletion',
            20018: 'Depreciation',
            20019: 'DepreciationAndAmortization',
            20020: 'DepreciationAmortizationDepletion',
            20205: 'DevelopmentExpense',
            20022: 'NetIncomeDiscontinuousOperations',
            20206: 'DividendIncome',
            20207: 'EarningLossOfEquityInvestments',
            20208: 'EarningsFromEquityInterest',
            20209: 'ElectricRevenue',
            20210: 'Equipment',
            20028: 'ExciseTaxes',
            20211: 'ExplorationDevelopmentAndMineralPropertyLeaseExpenses',
            20030: 'NetIncomeExtraordinary',
            20031: 'FeeRevenueAndOtherIncome',
            20212: 'Fees',
            20213: 'FeesAndCommissions',
            20214: 'ForeignExchangeTradingGains',
            20215: 'Fuel',
            20216: 'FuelAndPurchasePower',
            20217: 'GainOnSaleOfBusiness',
            20218: 'GainOnSaleOfPPE',
            20219: 'GainOnSaleOfSecurity',
            20220: 'GainsLossOnDisposalOfDiscontinuedOperations',
            20221: 'GasRevenue',
            20222: 'GeneralAccountAssets',
            20223: 'GeneralExpense',
            20045: 'GeneralAndAdministrativeExpense',
            20046: 'GrossProfit',
            20224: 'GrossPremiumsWritten',
            20225: 'ImpairmentOfCapitalAssets',
            20226: 'OtherImpairmentOfCapitalAssets',
            20227: 'IncomeFromEquityMethodInvestments',
            20228: 'AcquiredInProcessRnDIncome',
            20229: 'RestructringAndMnAIncome',
            20230: 'IncreaseDecreaseInNetUnearnedPremiumReserves',
            20231: 'InsuranceAndClaims',
            20232: 'InsuranceAndPremiums',
            20233: 'InterestIncomeFromInterestBearingDeposits',
            20057: 'InterestExpense',
            20234: 'InterestExpenseForCapitalizedLeaseObligations',
            20235: 'InterestExpenseForDeposit',
            20236: 'InterestExpenseForFederalFundsSoldAndSecuritiesPurchaseUnderAgreementsToResell',
            20237: 'InterestExpenseForLongTermDebt',
            20238: 'InterestExpenseForLongTermDebtAndCapitalSecurities',
            20239: 'InterestExpenseForShortTermDebt',
            20064: 'InterestExpenseNonOperating',
            20065: 'InterestExpenseOperating',
            20066: 'InterestIncomeAfterProvisionForLoanLoss',
            20240: 'InterestIncomeFromDeposits',
            20241: 'InterestIncomeFromFederalFundsSoldAndSecuritiesPurchaseUnderAgreementsToResell',
            20242: 'InterestIncomeFromInvestmentSecurities',
            20243: 'InterestIncomeFromLeases',
            20244: 'InterestIncomeFromLoans',
            20245: 'InterestIncomeFromLoansAndLease',
            20246: 'InterestIncomeFromSecurities',
            20247: 'InterestIncomeFromTradingAccountSecurities',
            20075: 'InterestIncomeNonOperating',
            20076: 'InterestIncomeOperating',
            20077: 'NetNonOperatingInterestIncomeExpense',
            20078: 'NetOperatingInterestIncomeExpense',
            20248: 'InvestmentBankingProfit',
            20249: 'LifeAnnuityPremiums',
            20250: 'LoansHeldForResell',
            20251: 'LossAndLossAdjustmentExpectedIncurred',
            20084: 'LossAdjustmentExpense',
            20252: 'MaintenanceAndRepairs',
            20253: 'MarketingExpense',
            20087: 'MinorityInterests',
            20254: 'InterestIncomeFromOtherMoneyMarketInvestments',
            20255: 'NetForeignExchangeGainLoss',
            20091: 'NetIncome',
            20093: 'NetIncomeCommonStockholders',
            20094: 'NetIncomeContinuousOperations',
            20095: 'NetInterestIncome',
            20096: 'NetInvestmentIncome',
            20256: 'NetOccupancyExpense',
            20257: 'NetPremiumsWritten',
            20258: 'NetRealizedGainLossOnInvestments',
            20100: 'TotalRevenue',
            20259: 'NonRecurringOperationExpense',
            20105: 'NonInterestExpense',
            20106: 'NonInterestIncome',
            20260: 'OccupancyAndEquipment',
            20108: 'OperatingExpense',
            20109: 'OperatingIncome',
            20112: 'OperatingRevenue',
            20261: 'OperatingTaxesnLicenses',
            20262: 'OperationAndMaintenance',
            20263: 'OtherCustomerServices',
            20264: 'OtherGainLossFromDispositionOfDiscontinuedOperations',
            20117: 'OtherIncomeExpense',
            20265: 'OtherInterestExpense',
            20266: 'OtherInterestIncome',
            20267: 'OtherNonInterestExpense',
            20268: 'OtherOperatingRevenue',
            20269: 'OtherSpecialCharges',
            20270: 'MiscOtherSpecialCharges',
            20271: 'OtherTaxes',
            20125: 'PolicyAcquisitionExpense',
            20272: 'PolicyFees',
            20273: 'PolicyholderBenefitsCeded',
            20274: 'PolicyholderBenefitsGross',
            20129: 'NetPolicyholderBenefitsAndClaims',
            20275: 'PolicyholderDividends',
            20276: 'PolicyholderInterest',
            20277: 'PolicyholderAndReinsurerAccounts',
            20278: 'TrustPreferredSecurities',
            20134: 'PreferredStockDividends',
            20135: 'TotalPremiumsEarned',
            20136: 'PretaxIncome',
            20279: 'PrincipleTransactionRevenue',
            20280: 'ProfessionalExpenseAndContractServicesExpense',
            20281: 'PromotionAndAdvertising',
            20282: 'PropertyCasualtyPremiums',
            20283: 'ProvisionForDoubtfulAccounts',
            20284: 'ProvisionForGainLossOnDisposal',
            20145: 'TaxProvision',
            20146: 'CreditLossesProvision',
            20285: 'PurchasedTransportationServices',
            20286: 'RealizedCapitalGain',
            20287: 'RentAndLandingFees',
            20288: 'ResearchExpense',
            20151: 'ResearchAndDevelopment',
            20289: 'RestructuringAndMergernAcquisition',
            20290: 'RevenuesCargo',
            20291: 'RevenuesPassenger',
            20292: 'SalariesAndWages',
            20293: 'SecuritiesActivities',
            20294: 'SellingExpense',
            20158: 'SellingAndMarketingExpense',
            20159: 'SellingGeneralAndAdministration',
            20295: 'ServiceChargeOnDepositorAccounts',
            20296: 'ShareInNetIncomeOfUnconsolidatedEntities',
            20162: 'SpecialIncomeCharges',
            20297: 'TimeDepositsPlaced',
            20164: 'TotalExpenses',
            20298: 'TradingGainLoss',
            20299: 'TransportationRevenue',
            20300: 'TrustFeesbyCommissions',
            20301: 'UnderwritingExpenses',
            20302: 'WriteDown',
            20303: 'OtherWriteDown',
            20304: 'WriteOff',
            20305: 'OtherWriteOff',
            20306: 'OtherNonInterestIncome',
            20307: 'PremiumTaxesCredit',
            20308: 'AmortizationOfIntangibles',
            20176: 'AmortizationOfDeferredAcquisitionCosts',
            20177: 'InterestIncome',
            20309: 'NetIncomeFromContinuingAndDiscontinuedOperation',
            20331: 'NetIncomeFromContinuingOperationNetMinorityInterest',
            20310: 'NetIncomeFromOtherGainsLosses',
            20311: 'NetIncomeFromTaxLossCarryforward',
            20312: 'OtherOperatingExpenses',
            20186: 'PropertyLiabilityInsuranceClaims',
            20313: 'TotalMoneyMarketInvestments',
            20314: 'ReconciledCostOfRevenue',
            20315: 'ReconciledDepreciation',
            20189: 'EarningBeforeInterestAndTax',
            20316: 'NormalizedIncome',
            20190: 'EBITDA',
            20317: 'NonOperatingExpenses',
            20318: 'NonOperatingIncome',
            20332: 'PrincipleInvestmentGainLoss',
            20333: 'GainLossonSaleofAssets',
            20334: 'GainonSaleofLoans',
            20335: 'GainonSaleofInvestmentProperty',
            20336: 'SpecialIncome',
            20337: 'AcquiredinProcessRnDIncomeBanks',
            20338: 'RestructuringAndMergerAndAcquisitionIncome',
            20339: 'ImpairmentofCapitalAssetsIncome',
            20340: 'GainonExtinguishmentofDebt',
            20342: 'SpecialCharge',
            20343: 'LossonExtinguishmentofDebt',
            20345: 'EarningsFromEquityInterestNetOfTax',
            20346: 'NetIncomeIncludingNoncontrollingInterests',
            20347: 'OtherunderPreferredStockDividend',
            20348: 'EarningsfromEquityInterestRevenue',
            20349: 'GainLossfromDisposalSaleofAssets',
            20350: 'GainLossfromDisposalSaleofAssetsOther',
            20351: 'GainonSaleofOtherRealEstateOwned',
            20352: 'InterestIncomeRevenue',
            20353: 'LitigationExpense',
            20354: 'OtherthanTemporaryImpairmentLossesInvestments',
            20355: 'UnrealizedGainorLoss',
            20356: 'ChangesinInventoriesofFinishedGoodsandWorkinProgress',
            20357: 'WorkPerformedbyEntityandCapitalized',
            20358: 'DistributionCosts',
            20359: 'StaffCosts',
            20360: 'SocialSecurityCosts',
            20361: 'PensionCosts',
            20363: 'OtherOperatingIncomeTotal',
            20364: 'ShareofOperatingProfitLossfromJointVenturesAndAssociates',
            20365: 'ExceptionalItems',
            20366: 'IncomefromSharesinSubsidiariesGroupUndertakings',
            20367: 'IncomefromAssociatesandOtherParticipatingInterests',
            20368: 'TotalOtherFinanceCost',
            20371: 'GrossDividendPayment',
            20376: 'InterestandSimilarIncome',
            20377: 'FeesandCommissionIncome',
            20378: 'FeesandCommissionExpense',
            20379: 'NetTradingIncome',
            20380: 'OutwardReinsurancePremiums',
            20381: 'OtherStaffCosts',
            20382: 'ShareBasedPayments',
            20383: 'GainonInvestmentProperties',
            20385: 'AverageDilutionEarn',
            20389: 'GainonRedemptionandExtinguishmentofDebt',
            20390: 'MiscellaneousOtherOperatingIncome',
            20391: 'GainLossonFinancialInstrumentsDesignatedasCashFlowHedges',
            20392: 'GainLossonDerecognitionofAvailableForSaleFinancialAssets',
            20393: 'GainLossonDerecognitionofNonCurrentAssetsNotHeldforSaleTotal',
            20394: 'NegativeGoodwillImmediatelyRecognized',
            20395: 'GainsLossesonFinancialInstrumentsDuetoFairValueAdjustmentsinHedgeAccountingTotal',
            20396: 'ImpairmentLossesReversalsFinancialInstrumentsNet',
            20397: 'ShareofProfitLossfromEquityAccountedInvestments',
            20400: 'ClaimsandPaidIncurred',
            20401: 'ReinsuranceRecoveriesClaimsandBenefits',
            20402: 'ChangeinInsuranceLiabilitiesNetofReinsurance',
            20405: 'ChangeinInvestmentContract',
            20408: 'ChangeinReinsuranceAssets',
            20409: 'CreditRiskProvisions',
            20411: 'WagesandSalaries',
            20412: 'OtherNonOperatingIncomeExpenses',
            20413: 'InterestIncomeOtherOperatingIncome',
            20414: 'OtherNonOperatingIncome',
            20415: 'OtherNonOperatingExpenses',
            20416: 'TotalUnusualItems',
            20417: 'TotalUnusualItemsExcludingGoodwill',
            20418: 'TaxRateForCalcs',
            20419: 'CalculatedTaxEffectOfUnusualItems',
            20420: 'NormalizedEBITDA',
            20421: 'GainOnForeignCurrencyExchangeFromBorrowingsRelatingToInterestCosts',
            20422: 'StockBasedCompensation',
            20423: '@isFileDate',
            20424: 'DilutedNIAvailtoComStockholders',
            20425: 'InvestmentContractLiabilitiesIncurred',
            20426: 'ReinsuranceRecoveriesofInvestmentContract',
            20429: 'TotalDividendPaymentofEquityShares',
            20430: 'TotalDividendPaymentofNonEquityShares',
            20431: 'ChangeinTheGrossProvisionforUnearnedPremiums',
            20432: 'ChangeinTheGrossProvisionforUnearnedPremiumsReinsurersShare',
            20433: 'ClaimsandChangeinInsuranceLiabilities',
            20434: 'ReinsuranceRecoveriesofInsuranceLiabilities',
            20445: 'TotalRevenueAsReported',
            20446: 'OperatingExpenseAsReported',
            20001: '@periodEndingDate',
            20002: '@fileDate',
            20003: '@accessionNumber',
            20004: '@formType',
            28005: '@isFYC',
            20441: 'NormalizedPretaxIncome',
            20442: 'ResearchAndDevelopmentExpensesSupplemental',
            20443: 'DepreciationSupplemental',
            20444: 'AmortizationSupplemental',
            28006: '@PeriodType',

            20447: 'ReportedNormalizedIncome',
            20448: 'ReportedNormalizedEBITDA',
            20449: 'ReportedNormalizedEBIT',
            20450: 'ReportedNormalizedOperatingProfit',
            20451: 'ReportedEffectiveTaxRate',
            20452: 'DisposalofBusinessesSupplemental',
            20453: 'DiscontinuedOperationsSupplemental',
            20454: 'AssetDisposalsSupplemental',
            20455: 'ImpairmentWriteOffWriteDownofCapitalAssetsSupplemental',
            20456: 'GoodwillImpairmentWriteOffSupplemental',
            20457: 'ImpairmentWriteOffWriteDownofOtherAssetsSupplemental',
            20458: 'GainLossonExtinguishmentofDebtSupplemental',
            20459: 'DebtRestructuringSupplemental',
            20460: 'LitigationIncomeExpenseSupplemental',
            20461: 'MergerandAcquisitionIncomeExpenseSupplemental',
            20462: 'RestructuringandReorganizationExpenseSupplemental',
            20463: 'OtherIrregularIncomeExpensesSupplemental'
        }

        self.BalanceSheet_mapping = {
            23000: 'AccountsPayable',
            23001: 'AccountsReceivable',
            23262: 'GrossAccountsReceivable',
            23263: 'NonCurrentAccountsReceivable',
            23004: 'CurrentAccruedExpenses',
            23005: 'NonCurrentAccruedExpenses',
            23264: 'AccruedInterestReceivable',
            23007: 'AccruedInvestmentIncome',
            23008: 'AccumulatedDepreciation',
            23009: 'GainsLossesNotAffectingRetainedEarnings',
            23012: 'AdditionalPaidInCapital',
            23265: 'AdvanceFromFederalHomeLoanBanks',
            23266: 'AllowanceForDoubtfulAccountsReceivable',
            23016: 'AllowanceForLoansAndLeaseLosses',
            23267: 'AllowanceForNotesReceivable',
            23268: 'AssetsHeldForSale',
            23269: 'AssetsOfDiscontinuedOperations',
            23020: 'AvailableForSaleSecurities',
            23270: 'BankAcceptanceExecutedAndOutstanding',
            23271: 'BankIndebtedness',
            23272: 'BankLoan',
            23273: 'BankOwnedLifeInsurance',
            23274: 'SecurityBorrowed',
            23275: 'BuildingsAndImprovements',
            23027: 'CapitalStock',
            23028: 'Cash',
            23029: 'CashEquivalents',
            23030: 'CashAndCashEquivalents',
            23031: 'CashAndDueFromBanks',
            23032: 'CashCashEquivalentsAndFederalFundsSold',
            23033: 'CashCashEquivalentsAndShortTermInvestments',
            23276: 'CasualtyClaims',
            23277: 'CededUnearnedPremiums',
            23278: 'CommercialLoan',
            23279: 'CommercialPaper',
            23038: 'CommonStock',
            23280: 'CommonStockEquity',
            23281: 'CommonStocksAvailableForSale',
            23282: 'ConstructionInProgress',
            23283: 'ConsumerLoan',
            23284: 'MinimumPensionLiabilities',
            23044: 'CurrentAssets',
            23045: 'CurrentDebt',
            23046: 'CurrentDebtAndCapitalLeaseObligation',
            23047: 'CurrentLiabilities',
            23048: 'CurrentCapitalLeaseObligation',
            23285: 'CustomerAcceptances',
            23286: 'DeferredAcquisitionCosts',
            23052: 'DeferredAssets',
            23054: 'DeferredCosts',
            23287: 'DeferredFinancingCosts',
            23057: 'NonCurrentDeferredLiabilities',
            23058: 'CurrentDeferredLiabilities',
            23059: 'DeferredPolicyAcquisitionCosts',
            23061: 'CurrentDeferredRevenue',
            23062: 'NonCurrentDeferredRevenue',
            23063: 'DeferredTaxAssets',
            23064: 'CurrentDeferredTaxesAssets',
            23065: 'CurrentDeferredTaxesLiabilities',
            23066: 'NonCurrentDeferredTaxesAssets',
            23067: 'NonCurrentDeferredTaxesLiabilities',
            23288: 'DefinedPensionBenefit',
            23289: 'DerivativeProductLiabilities',
            23290: 'DerivativeAssets',
            23291: 'DividendsPayable',
            23292: 'ESOPDebtGuarantee',
            23293: 'EmployeeBenefits',
            23076: 'EquityInvestments',
            23294: 'FacilitiesAndOther',
            23295: 'FederalFundsPurchased',
            23079: 'FederalFundsPurchasedAndSecuritiesSoldUnderAgreementToRepurchase',
            23296: 'FederalFundsSold',
            23081: 'FederalFundsSoldAndSecuritiesPurchaseUnderAgreementsToResell',
            23297: 'FederalHomeLoanBankStock',
            23298: 'FinancialAssets',
            23299: 'FinancialInstrumentsSoldUnderAgreementsToRepurchase',
            23300: 'FinishedGoods',
            23086: 'FixedMaturitiesAvailableForSale',
            23087: 'FixedMaturitiesHeldToMaturity',
            23088: 'FixedMaturitiesTrading',
            23089: 'FixedMaturityInvestments',
            23301: 'FlightFleetVehicleAndRelatedEquipments',
            23302: 'ForeclosedAssets',
            23303: 'ForeignComponent',
            23304: 'ForeignCurrencyTranslationAdjustments',
            23305: 'FuelAndNaturalGas',
            23095: 'FuturePolicyBenefits',
            23096: 'GeneralPartnershipCapital',
            23097: 'Goodwill',
            23098: 'GoodwillAndOtherIntangibleAssets',
            23099: 'GrossLoan',
            23100: 'GrossPPE',
            23306: 'GuaranteedInvestmentContract',
            23102: 'HeldToMaturitySecurities',
            23103: 'IncomeTaxPayable',
            23105: 'InterestBearingDepositsLiabilities',
            23106: 'InterestPayable',
            23107: 'InterestBearingDepositsAssets',
            23108: 'Inventory',
            23307: 'InventoriesAdjustmentsAllowances',
            23308: 'InvestmentTaxCredits',
            23111: 'InvestmentsAndAdvances',
            23309: 'InvestmentsInAffiliatesSubsidiariesAssociatesAndJointVentures',
            23310: 'InvestmentsInOtherVenturesUnderEquityMethod',
            23311: 'InvestmentsInVariableInterestEntity',
            23312: 'LandAndImprovements',
            23313: 'Leases',
            23314: 'LiabilitiesOfDiscontinuedOperations',
            23118: 'LimitedPartnershipCapital',
            23315: 'LimitedPartnership',
            23316: 'LineOfCredit',
            23317: 'LoansHeldForSale',
            23318: 'LoansReceivable',
            23123: 'LongTermDebt',
            23124: 'LongTermDebtAndCapitalLeaseObligation',
            23126: 'LongTermEquityInvestment',
            23127: 'LongTermCapitalLeaseObligation',
            23319: 'MachineryFurnitureEquipment',
            23320: 'MaterialsAndSupplies',
            23321: 'MineralProperties',
            23132: 'MinorityInterest',
            23133: 'MoneyMarketInvestments',
            23322: 'MortgageLoan',
            23323: 'MortgageAndConsumerloans',
            23324: 'NaturalResourceAssets',
            23137: 'NetLoan',
            23325: 'NetOtherUnrealizedGainLoss',
            23139: 'NetPPE',
            23326: 'NetUnrealizedGainLossForeignCurrency',
            23327: 'NetUnrealizedGainLossInvestments',
            23142: 'NonInterestBearingDeposits',
            23143: 'CurrentNotesPayable',
            23144: 'NotesReceivable',
            23328: 'GrossNotesReceivable',
            23146: 'NonCurrentNoteReceivables',
            23329: 'OtherAssets',
            23330: 'OtherCapitalStock',
            23331: 'OtherCurrentAssets',
            23332: 'OtherCurrentBorrowings',
            23151: 'OtherCurrentLiabilities',
            23333: 'OtherDeferredCosts',
            23334: 'OtherDeposits',
            23335: 'OtherEquityAdjustments',
            23155: 'OtherIntangibleAssets',
            23336: 'OtherInterestEarningAssets',
            23337: 'OtherInventories',
            23338: 'OtherInvestedAssets',
            23339: 'OtherNonCurrentAssets',
            23340: 'OtherProperties',
            23341: 'OtherRealEstateOwned',
            23342: 'OtherReceivables',
            23163: 'ShortTermInvestments',
            23343: 'Patents',
            23165: 'Payables',
            23166: 'PayablesAndAccruedExpenses',
            23344: 'NonCurrentPensionAndOtherPostretirementBenefitPlans',
            23345: 'PolicyLoans',
            23169: 'TotalPolicyHoldersLiabilities',
            23171: 'PolicyholderFunds',
            23172: 'PreferredSecuritiesOutsideStockEquity',
            23174: 'PreferredStock',
            23347: 'PreferredStockEquity',
            23348: 'PreferredStockOfSubsidiary',
            23349: 'PreferredStocksAvailableForSale',
            23178: 'PremiumsReceivable',
            23179: 'PrepaidAssets',
            23180: 'NonCurrentPrepaidAssets',
            23350: 'PrepaidReinsurancePremiums',
            23351: 'Properties',
            23352: 'CurrentProvisions',
            23353: 'LongTermProvisions',
            23354: 'PurchasedComponents',
            23355: 'RawMaterials',
            23356: 'RealEstateHeldForSale',
            23357: 'RealEstateAndRealEstateJointVenturesHeldForInvestment',
            23189: 'Receivables',
            23358: 'RecievablesAdjustmentsAllowances',
            23191: 'RedeemablePreferredStock',
            23359: 'RegulatoryAssets',
            23360: 'RegulatoryLiabilities',
            23361: 'ReinsuranceBalancesPayable',
            23362: 'ReinsuranceReceivables',
            23196: 'ReinsuranceRecoverable',
            23363: 'ReinsuranceRecoverableForPaidLosses',
            23364: 'ReinsuranceRecoverableForUnpaidLosses',
            23365: 'RestrictedCash',
            23366: 'RestrictedCashAndCashEquivalents',
            23367: 'RestrictedCashAndInvestments',
            23368: 'RestrictedCommonStock',
            23369: 'RestrictedInvestments',
            23204: 'RetainedEarnings',
            23205: 'SecuritiesLendingCollateral',
            23370: 'SecuritiesLendingPayable',
            23207: 'SecurityAgreeToBeResell',
            23208: 'SecuritySoldNotYetRepurchased',
            23209: 'SeparateAccountAssets',
            23210: 'SeparateAccountLiability',
            23212: 'ShortTermInvestmentsAvailableForSale',
            23213: 'ShortTermInvestmentsHeldToMaturity',
            23214: 'ShortTermInvestmentsTrading',
            23215: 'StockholdersEquity',
            23371: 'StudentLoan',
            23217: 'TotalTaxPayable',
            23372: 'TaxesReceivable',
            23373: 'TimeDepositsPlaced',
            23220: 'TotalAssets',
            23374: 'TotalCapitalization',
            23375: 'TotalDeferredCreditsAndOtherNonCurrentLiabilities',
            23223: 'TotalDeposits',
            23224: 'TotalInvestments',
            23225: 'TotalLiabilities',
            23259: 'TotalLiabilitiesNetMinorityInterest',
            23226: 'TotalNonCurrentAssets',
            23227: 'TotalNonCurrentLiabilities',
            23260: 'TotalNonCurrentLiabilitiesNetMinorityInterest',
            23228: 'TotalPartnershipCapital',
            23229: 'TradingAssets',
            23230: 'TradingLiabilities',
            23231: 'TradingSecurities',
            23232: 'TreasuryStock',
            23376: 'UnbilledReceivables',
            23235: 'UnearnedIncome',
            23236: 'UnearnedPremiums',
            23237: 'UnpaidLossAndLossReserve',
            23377: 'UnrealizedGainLoss',
            23378: 'WorkInProcess',
            23379: 'OtherNonCurrentLiabilities',
            23380: 'CapitalLeaseObligations',
            23381: 'OtherLiabilities',
            23382: 'OtherPayable',
            23245: 'InvestedCapital',
            23383: 'TangibleBookValue',
            23384: 'TotalEquity',
            23261: 'TotalEquityGrossMinorityInterest',
            23385: 'WorkingCapital',
            23386: 'TotalDebt',
            23387: 'CashValueOfLifeInsurance',
            23388: 'CommonUtilityPlant',
            23252: 'CurrentDeferredAssets',
            23253: 'NonCurrentDeferredAssets',
            23389: 'ElectricUtilityPlant',
            23390: 'NaturalGasFuelAndOther',
            23391: 'NetUtilityPlant',
            23392: 'WaterProduction',
            23258: 'SecuritiesAndInvestments',
            23393: 'OrdinarySharesNumber',
            23394: 'PreferredSharesNumber',
            23395: 'TreasurySharesNumber',
            23399: 'TradingAndOtherReceivable',
            23400: 'EquityAttributableToOwnersOfParent',
            23401: 'SecuritiesLoaned',
            23402: 'ParticipatingPolicyholderEquity',
            23403: 'NetTangibleAssets',
            23404: 'DuefromRelatedPartiesCurrent',
            23405: 'DuefromRelatedPartiesNonCurrent',
            23406: 'DuetoRelatedParties',
            23407: 'DuetoRelatedPartiesCurrent',
            23408: 'DuetoRelatedPartiesNonCurrent',
            23409: 'NetAssets',
            23410: 'InvestmentProperties',
            23411: 'InvestmentsinSubsidiariesatCost',
            23412: 'InvestmentsinAssociatesatCost',
            23413: 'InvestmentsinJointVenturesatCost',
            23414: 'InvestmentinFinancialAssets',
            23415: 'FinanceLeaseReceivables',
            23418: 'ConvertibleLoansCurrent',
            23419: 'BankLoansCurrent',
            23420: 'OtherLoansCurrent',
            23422: 'AccruedandDeferredIncome',
            23426: 'BankLoansNonCurrent',
            23427: 'OtherLoansNonCurrent',
            23430: 'OtherReserves',
            23432: 'LoansandAdvancestoBank',
            23433: 'LoansandAdvancestoCustomer',
            23434: 'TreasuryBillsandOtherEligibleBills',
            23435: 'EquitySharesInvestments',
            23436: 'DepositsbyBank',
            23437: 'CustomerAccounts',
            23438: 'ItemsinTheCourseofTransmissiontoOtherBanks',
            23439: 'TradingandFinancialLiabilities',
            23440: 'DebtSecuritiesinIssue',
            23441: 'SubordinatedLiabilities',
            23443: 'ProvisionsTotal',
            23444: 'OperatingLeaseAssets',
            23445: 'ClaimsOutstanding',
            23447: 'LongTermContracts',
            23448: 'RealEstate',
            23451: 'PaymentofBills',
            23452: 'LiabilitiesHeldforSaleCurrent',
            23453: 'LiabilitiesHeldforSaleNonCurrent',
            23454: 'UnclassifiedCurrentAssets',
            23455: 'DebtSecurities',
            23456: 'TotalFinancialLeaseObligations',
            23457: 'AccruedandDeferredIncomeCurrent',
            23458: 'AccruedandDeferredIncomeNonCurrent',
            23459: 'FinanceLeaseReceivablesCurrent',
            23460: 'FinanceLeaseReceivablesNonCurrent',
            23462: 'FinancialLiabilitiesCurrent',
            23463: 'FinancialLiabilitiesNonCurrent',
            23466: 'FinancialAssetsDesignatedasFairValueThroughProfitorLossTotal',
            23468: 'TaxesAssetsCurrent',
            23469: 'OtherEquityInterest',
            23470: 'InterestBearingBorrowingsNonCurrent',
            23471: 'NonInterestBearingBorrowingsNonCurrent',
            23472: 'TradeandOtherPayablesNonCurrent',
            23473: 'InterestBearingBorrowingsCurrent',
            23474: 'NonInterestBearingBorrowingsCurrent',
            23475: 'PensionandOtherPostRetirementBenefitPlansCurrent',
            23476: 'CashandBalanceswithCentralBanks',
            23477: 'PlacementwithBanksandOtherFinancialInstitutions',
            23478: 'OtherLoanAssets',
            23479: 'HedgingAssetsTotal',
            23480: 'AssetsPledgedasCollateralSubjecttoSaleorRepledgingTotal',
            23481: 'TaxAssetsTotal',
            23482: 'AdvancesfromCentralBanks',
            23483: 'CertificatesofDepositsandOtherDebtSecuritiesIssued',
            23484: 'DepositCertificates',
            23485: 'DebenturesandDebtCertificates',
            23486: 'InterestBearingBorrowingsTotal',
            23487: 'NonInterestBearingBorrowingsTotal',
            23488: 'OtherBorrowedFunds',
            23490: 'FinancialLiabilitiesDesignatedasFairValueThroughProfitorLossTotal',
            23491: 'FinancialLiabilitiesMeasuredatAmortizedCostTotal',
            23492: 'LoanCapital',
            23493: 'HedgingLiabilitiesTotal',
            23494: 'LiabilitiesRecognizedforFairValueChangesinPortfolioHedgeofInterestRateRisk',
            23495: 'AccruedLiabilitiesTotal',
            23496: 'DeferredIncomeTotal',
            23497: 'DeferredTaxLiabilitiesTotal',
            23499: 'ReinsuranceAssets',
            23500: 'ReinsuranceShareofInsuranceContract',
            23501: 'ReinsuranceShareofAccruedPolicyholderClaims',
            23502: 'DepositsMadeunderAssumedReinsuranceContract',
            23503: 'InsuranceContractAssets',
            23504: 'InsuranceReceivables',
            23505: 'InsuranceContractLiabilities',
            23506: 'InsurancePayables',
            23508: 'DepositsReceivedunderCededInsuranceContract',
            23509: 'InvestmentContractLiabilities',
            23511: 'ConstructionGrants',
            23514: 'DeferredCostCurrent',
            23515: 'PensionAndOtherPostretirementBenefitPlansTotal',
            23516: 'LiabilitiesHeldforSaleTotal',
            23517: 'HedgingAssetsNonCurrent',
            23518: 'HedgingAssetsCurrent',
            23519: 'ConvertibleLoansTotal',
            23520: 'BankLoansTotal',
            23521: 'OtherLoansTotal',
            23522: 'HedgingLiabilitiesNonCurrent',
            23523: 'HedgingLiabilitiesCurrent',
            23524: 'InsuranceFundsNonCurrent',
            23525: 'InsuranceFundsCurrent',
            23528: 'DebtTotal',
            23529: 'ComTreShaNum',
            23530: 'PreTreShaNum',
            23531: 'NetDebt',
            23532: 'ShareIssued',
            23533: 'AssetsHeldForSaleCurrent',
            23534: 'AssetsHeldForSaleNonCurrent',
            23535: 'BiologicalAssets',
            23536: 'CashRestrictedOrPledged',
            23537: 'ConvertibleLoansNonCurrent',
            23538: 'FinancialOrDerivativeInvestmentCurrentLiabilities',
            23539: 'LoanAndLoanReceivables',
            23540: 'OtherInvestments',
            23541: 'TradeAndOtherReceivablesNonCurrent',
            23542: '@bsFileDate',
            23543: 'DuefromRelatedParties',
            23544: 'TrustPreferredSecurities',
            23545: 'CooperativesShareCapitalRepayableonDemand',
            23546: 'UnallocatedSurplus',
            23547: 'DebtDueInYear1',
            23548: 'DebtDueInYear2',
            23549: 'DebtDueInYear5',
            23550: 'DebtDueBeyond',
            23551: 'TotalDebtInMaturitySchedule',
            23556: 'TotalLiabilitiesAsReported',
            23557: 'TotalEquityAsReported',
        }

        self.CashFlow_mapping = {
            26000: 'Amortization',
            26141: 'AmortizationOfFinancingCostsAndDiscounts',
            26142: 'AmortizationOfSecurities',
            26143: 'AssetImpairmentCharge',
            26004: 'CallsMaturitiesOfMaturitySecurities',
            26005: 'CapitalExpenditure',
            26006: 'NetCapitalExpenditureDisposals',
            26007: 'CashDividendsPaid',
            26008: 'CashFlowFromContinuingFinancingActivities',
            26009: 'CashFlowFromContinuingInvestingActivities',
            26010: 'CashFlowFromContinuingOperatingActivities',
            26011: 'CashFlowFromDiscontinuedOperation',
            26012: 'FinancingCashFlow',
            26013: 'InvestingCashFlow',
            26014: 'OperatingCashFlow',
            26015: 'BeginningCashPosition',
            26016: 'EndCashPosition',
            26017: 'CashFromDiscontinuedFinancing',
            26018: 'CashFromDiscontinuedFinancingActivities',
            26019: 'CashFromDiscontinuedInvesting',
            26020: 'CashFromDiscontinuedInvestingActivities',
            26021: 'CashFromDiscontinuedOperating',
            26022: 'ChangeInAccountPayable',
            26144: 'ChangeInDividendPayable',
            26024: 'ChangeInTaxPayable',
            26025: 'ChangeInAccruedExpense',
            26026: 'ChangeInAccruedInvestmentIncome',
            26027: 'ChangesInCash',
            26028: 'ChangeInDeferredAcquisitionCosts',
            26145: 'ChangeInDeferredCharges',
            26030: 'ChangeInFederalFundsAndSecuritiesSoldForRepurchase',
            26031: 'ChangeInFundsWithheld',
            26032: 'ChangeInIncomeTaxPayable',
            26033: 'ChangeInInterestPayable',
            26034: 'ChangeInInventory',
            26035: 'ChangeInLoans',
            26036: 'ChangeInLossAndLossAdjustmentExpenseReserves',
            26146: 'ChangeInOtherCurrentAssets',
            26147: 'ChangeInOtherCurrentLiabilities',
            26148: 'ChangeInOtherWorkingCapital',
            26040: 'ChangeInPayable',
            26041: 'ChangeInPayablesAndAccruedExpense',
            26042: 'ChangeInPremiumsReceivable',
            26043: 'ChangeInPrepaidAssets',
            26149: 'ChangeInPrepaidReinsurancePremiums',
            26045: 'ChangeInReceivables',
            26150: 'ChangeInReinsuranceReceivableOnPaidLosses',
            26047: 'ChangeInReinsuranceRecoverableOnPaidAndUnpaidLosses',
            26151: 'ChangeInReinsuranceRecoverableOnUnpaidLosses',
            26049: 'ChangeInRestrictedCash',
            26050: 'ChangeInTradingAccountSecurities',
            26152: 'ChangeInUnearnedPremiums',
            26153: 'ChangeInUnearnedPremiumsCeded',
            26053: 'ChangeInWorkingCapital',
            26154: 'CommonStockDividendPaid',
            26055: 'CumulativeEffectOfAccountingChange',
            26056: 'DeferredIncomeTax',
            26057: 'DeferredTax',
            26058: 'Depletion',
            26059: 'Depreciation',
            26060: 'DepreciationAndAmortization',
            26061: 'DepreciationAmortizationDepletion',
            26155: 'EarningsLossesFromEquityInvestments',
            26063: 'EffectOfExchangeRateChanges',
            26156: 'ExcessTaxBenefitFromStockBasedCompensation',
            26157: 'ExtraordinaryItems',
            26158: 'GainLossOnInvestmentSecurities',
            26159: 'GainLossOnSaleOfBusiness',
            26160: 'GainLossOnSaleOfPPE',
            26069: 'IncreaseDecreaseInDeposit',
            26161: 'InterestCreditedOnPolicyholderDeposits',
            26162: 'CashFromDiscontinuedOperatingActivities',
            26071: 'NetCommonStockIssuance',
            26072: 'NetIssuancePaymentsOfDebt',
            26073: 'NetLongTermDebtIssuance',
            26074: 'NetPreferredStockIssuance',
            26075: 'NetShortTermDebtIssuance',
            26077: 'NetCashFromDiscontinuedOperations',
            26078: 'NetForeignCurrencyExchangeGainLoss',
            26079: 'NetIncome',
            26080: 'NetIncomeFromContinuingOperations',
            26163: 'OperatingGainsLosses',
            26164: 'NetOtherFinancingCharges',
            26165: 'NetOtherInvestingChanges',
            26166: 'OtherNonCashItems',
            26087: 'PaymentForLoans',
            26088: 'CommonStockPayments',
            26089: 'PreferredStockPayments',
            26090: 'LongTermDebtPayments',
            26091: 'ShortTermDebtPayments',
            26167: 'PensionAndEmployeeBenefitExpense',
            26168: 'PreferredStockDividendPaid',
            26094: 'ProceedsFromIssuanceOfWarrants',
            26095: 'ProceedsFromLoans',
            26097: 'ProceedsFromStockOptionExercised',
            26098: 'CommonStockIssuance',
            26099: 'LongTermDebtIssuance',
            26100: 'PreferredStockIssuance',
            26101: 'ShortTermDebtIssuance',
            26169: 'ProceedsPaymentFederalFundsSoldAndSecuritiesPurchasedUnderAgreementToResell',
            26103: 'NetProceedsPaymentForLoan',
            26104: 'ProceedsPaymentInInterestBearingDepositsInBank',
            26170: 'ProvisionForLoanLeaseAndOtherLosses',
            26106: 'PurchaseOfEquitySecurities',
            26107: 'PurchaseOfFixedMaturitySecurities',
            26108: 'PurchaseOfIntangibles',
            26110: 'PurchaseOfInvestment',
            26111: 'PurchaseOfLongTermInvestments',
            26112: 'PurchaseOfPPE',
            26113: 'PurchaseOfShortTermInvestments',
            26114: 'PurchaseOfTechnology',
            26115: 'PurchaseOfBusiness',
            26116: 'NetBusinessPurchaseAndSale',
            26117: 'NetIntangiblesPurchaseAndSale',
            26118: 'NetInvestmentPurchaseAndSale',
            26119: 'NetPPEPurchaseAndSale',
            26121: 'NetTechnologyPurchaseAndSale',
            26171: 'RealizedGainLossOnSaleOfLoansAndLease',
            26123: 'SaleOfBusiness',
            26124: 'SaleOfIntangibles',
            26125: 'SaleOfInvestment',
            26126: 'SaleOfLongTermInvestments',
            26127: 'SaleOfPPE',
            26128: 'SaleOfShortTermInvestments',
            26129: 'SaleOfTechnology',
            26130: 'SalesOfEquitySecurities',
            26131: 'SalesOfFixedMaturitySecurities',
            26172: 'StockBasedCompensation',
            26173: 'UnrealizedGainLossOnInvestmentSecurities',
            26174: 'UnrealizedGainsLossesOnDerivatives',
            26175: 'AmortizationOfIntangibles',
            26176: 'AllowanceForFundsConstruction',
            26137: 'ChangesInAccountReceivables',
            26177: 'DomesticSales',
            26178: 'ForeignSales',
            26179: 'IncomeTaxPaidSupplementalData',
            26180: 'InterestPaidSupplementalData',
            26181: 'IssuanceOfCapitalStock',
            26182: 'IssuanceOfDebt',
            26183: 'RepaymentOfDebt',
            26184: 'RepurchaseOfCapitalStock',
            26185: 'FreeCashFlow',
            26186: 'DirectCashFlowsFromOperatingActivities',
            26188: 'DecreaseinInterestBearingDepositsinBank',
            26189: 'IncreaseinInterestBearingDepositsinBank',
            26190: 'AdjustedGeographySegmentData',
            26194: 'InterestReceivedCFO',
            26195: 'InterestPaidCFO',
            26196: 'PurchaseofSubsidiaries',
            26197: 'PurchaseofJointVentureAssociate',
            26198: 'SaleofSubsidiaries',
            26199: 'SaleofJointVentureAssociate',
            26200: 'IncreaseDecreaseinLeaseFinancing',
            26201: 'IncreaseinLeaseFinancing',
            26202: 'RepaymentinLeaseFinancing',
            26203: 'ShareofAssociates',
            26204: 'ProfitonDisposals',
            26205: 'ReorganizationOtherCosts',
            26206: 'OtherFinancing',
            26207: 'NetOutwardLoans',
            26208: 'IssueExpenses',
            26211: 'ChangeinCertificatesofDepositsandDebtSecuritiesIssued',
            26212: 'PaymentstoAcquireHeldToMaturityInvestments',
            26213: 'PaymentstoAcquireAvailableForSaleFinancialAssets',
            26214: 'PaymentstoAcquireFinancialAssetsDesignatedasFairValue',
            26215: 'ProceedsfromDisposalofHeldToMaturityInvestments',
            26216: 'ProceedsfromDisposalofAvailableForSaleFinancialAssets',
            26217: 'ProceedsfromDisposalofFinancialAssetsDesignatedasFairValue',
            26218: 'ChangeinFairValueofInvestmentProperties',
            26219: 'ChangeinDepositsbyBanksandCustomers',
            26220: 'CashFlowsfromusedinOperatingActivitiesDirect',
            26221: 'ClassesofCashReceiptsfromOperatingActivities',
            26222: 'OtherCashReceiptsfromOperatingActivities',
            26223: 'ClassesofCashPayments',
            26224: 'PaymentstoSuppliersforGoodsandServices',
            26225: 'PaymentsfromContractsHeldforDealingorTradingPurpose',
            26226: 'PaymentsonBehalfofEmployees',
            26227: 'PaymentsforPremiumsandClaimsAnnuitiesandOtherPolicyBenefits',
            26228: 'OtherCashPaymentsfromOperatingActivities',
            26229: 'DividendsPaidDirect',
            26230: 'DividendsReceivedDirect',
            26231: 'InterestPaidDirect',
            26232: 'InterestReceivedDirect',
            26233: 'TaxesRefundPaidDirect',
            26234: 'TotalAdjustmentsforNonCashItems',
            26235: 'ImpairmentLossReversalRecognizedinProfitorLoss',
            26236: 'AdjustmentsforUndistributedProfitsofAssociates',
            26237: 'OtherAdjustmentsforWhichCashEffectsAreInvestingorFinancingCashFlow',
            26238: 'DividendPaidCFO',
            26239: 'DividendReceivedCFO',
            26240: 'TaxesRefundPaid',
            26241: 'OtherOperatingInflowsOutflowsofCash',
            26242: 'ProceedsfromGovernmentGrantsCFI',
            26243: 'CashAdvancesandLoansMadetoOtherParties',
            26244: 'CashReceiptsfromRepaymentofAdvancesandLoansMadetoOtherParties',
            26245: 'CashReceiptsfromPaymentsforFinancialDerivativeContracts',
            26246: 'DividendsReceivedCFI',
            26247: 'InterestReceivedCFI',
            26248: 'IncomeTaxesRefundPaidCFI',
            26249: 'IssuancePaymentofOtherEquityInstrumentsNet',
            26250: 'PaymentsofOtherEquityInstruments',
            26251: 'ProceedsfromIssuingOtherEquityInstruments',
            26252: 'ProceedsfromGovernmentGrantsCFF',
            26253: 'InterestPaidCFF',
            26254: 'IncomeTaxesRefundPaidCFF',
            26255: 'ChangeinAccruedIncome',
            26256: 'ChangeinDeferredIncome',
            26258: 'ChangeinFinancialAssets',
            26259: 'ChangeinAdvancesfromCentralBanks',
            26260: 'ChangeinFinancialLiabilities',
            26261: 'ChangeinInsuranceContractAssets',
            26262: 'ChangeinReinsuranceReceivables',
            26263: 'ChangeinDeferredAcquisitionCostsNet',
            26264: 'ChangeinInsuranceFunds',
            26265: 'ChangeinReinsurancePayables',
            26266: 'ChangeinInvestmentContractLiabilities',
            26267: 'ChangeinInsuranceContractLiabilities',
            26269: 'ProvisionandWriteOffofAssets',
            26270: 'ReceiptsfromCustomers',
            26271: 'ReceiptsfromGovernmentGrants',
            26272: 'MinorityInterest',
            26273: 'CapitalExpenditureReported',
            26274: 'CashReceiptsfromTaxRefunds',
            26275: 'CashReceiptsfromBorrowings',
            26276: 'CashReceiptsfromDepositsbyBanksandCustomers',
            26277: 'CashReceiptsfromLoans',
            26278: 'CashReceiptsfromSecuritiesRelatedActivities',
            26279: 'CashReceiptsfromDecreaseinAssets',
            26280: 'CashReceiptsfromFeesandCommissions',
            26281: 'CashPaymentsforBorrowings',
            26282: 'CashPaymentsforDepositsbyBanksandCustomers',
            26283: 'CashPaymentsforLoans',
            26284: 'InterestandCommissionPaid',
            26285: 'AllTaxesPaid',
            26286: 'CashReceivedfromInsuranceActivities',
            26287: 'PremiumReceived',
            26288: 'ReinsuranceandOtherRecoveriesReceived',
            26289: 'PolicyholderDepositInvestmentReceived',
            26290: 'CashPaidforInsuranceActivities',
            26291: 'ClaimsPaid',
            26292: 'CommissionPaid',
            26293: 'CashPaidtoReinsurers',
            26294: 'OtherUnderwritingExpensesPaid',
            26295: 'CashDividendsForMinorities',
            26296: '@cfFileDate',
            26297: 'NetIncomeFromDiscontinuedOperations',
            26298: 'CashGeneratedfromOperatingActivities',
            26299: 'FundFromOperation',
            26305: 'ChangeinCashSupplementalAsReported'
        }

        self.Misc_mapping = {
            28004: 'TotalRiskBasedCapitalRatio',
            28000: 'AuditorName',
            28001: 'AuditorReportStatus',
            28002: 'InventoryValuationMethod',
            28003: 'NumberOfShareHolders'
        }

        self.init_url = 'http://geexoidevap8002.morningstar.com/' \
                           'DataOutput.aspx?package=%s&Content=%s&IdType=%s' \
                           '&Id=%s&ReportType=%s&Dates=%s'

    # 检查传入的记录的值可以可以在xml中找到
    def check_value(self, line_value):
        flag = False
        values = self.parse_line_value(line_value)

        # 使用xpath解析xml
        tree2 = etree.XML(self.content.encode('utf-8'))

        if values['targetNode'] == None:
            self.log_exoi.error("{0}'s DataId {1} is not exists".format(line_value, line_value.split('|')[1]))
            return

        # 这里要区分点的类型是IncomeStatement，CashFlow, BalanceSheet.
        if "@" not in values['targetNode']:
            path = self.get_path(values)
            target_node = tree2.xpath(path)
            if len(target_node) == 1 and target_node[0].text == values.get(values.get('targetNode')):
                flag = True
        else:
            path = self.get_attr_path(values)
            target_node = tree2.xpath(path)
            if len(target_node) == 1:
                flag = True

        return flag

    # 把每一行的数据转换为一个字典，方便查询
    def parse_line_value(self, line_value):
        values = {
            'companyId': '',
            'asOf': '',
            'reportType': '',
            'fiscalYearEnd': '',
            'numberOfMonth': '',
            'isDerived': ''}
        value_set = line_value.split('|')  # value_set最后的两个要被解析成节点和值的对应
        values['companyId'] = value_set[0]
        self.get_node_type(values, value_set)
        values['asOf'] = value_set[3]
        values['numberOfMonth'] = value_set[4].replace('M', "")
        values['fiscalYearEnd'] = value_set[5]
        values['currencyId'] = 'CU$$$$$' + value_set[6]
        values['reportType'] = value_set[7]
        values['isDerived'] = value_set[8]

        return values

    # 因为一个DataId可能出现在不用的IdMapping中.所以需要做特别的处理,并增加key nodeType
    def get_node_type(self, values, value_set):
        dataId = int(value_set[1])
        if self.IncomeStatement_mapping.get(dataId):
            values['nodeType'] = 'IncomeStatements'
            values['targetNode'] = self.IncomeStatement_mapping.get(int(value_set[1]))  # values['targetNode']=DataId对应的节点的名字
            values[self.IncomeStatement_mapping.get(int(value_set[1]))] = value_set[2]  # Values[DataId对应的节点名] = DataId的节点值
        elif self.BalanceSheet_mapping.get(dataId):
            values['nodeType'] = 'BalanceSheets'
            values['targetNode'] = self.BalanceSheet_mapping.get(int(value_set[1]))
            values[self.BalanceSheet_mapping.get(int(value_set[1]))] = value_set[2]
        elif self.CashFlow_mapping.get(dataId):
            values['nodeType'] = 'CashFlow'
            values['targetNode'] = self.CashFlow_mapping.get(int(value_set[1]))
            values[self.CashFlow_mapping.get(int(value_set[1]))] = value_set[2]
        elif self.Misc_mapping.get(dataId):
            values['nodeType'] = 'MiscInfo'
            values['targetNode'] = self.Misc_mapping.get(int(value_set[1]))
            values[self.Misc_mapping.get(int(value_set[1]))] = value_set[2]

    # 解析line，找出拼接URL需要的参数
    def parse_line(self, line_value):
        param = {'Package': 'EquityData',
                 'Content': 'Fundamental',
                 'IdType': 'EquityCompanyId',
                 'Id': '',
                 'Dates': '',
                 'ReportType': ''}

        values = line_value.split("|")
        Id = values[0]
        Dates = time.strptime(values[3], "%Y-%m-%d").tm_year
        reportType = values[7]
        param['ReportType'] = reportType
        param['Id'] = Id
        param['Dates'] = Dates

        return param

    # 产生完整的URL
    def construct_url(self, param):
        # 把所有的key转换为小写的
        a_lower = {k.lower(): v for k, v in param.items()}
        package = a_lower.get('package'.lower())
        content = a_lower.get('content'.lower())
        Id = a_lower.get('Id'.lower())
        IdType = a_lower.get('IdType'.lower())
        Dates = a_lower.get('Dates'.lower())
        ReportType = a_lower.get('ReportType'.lower())
        intact_url = self.init_url % (package, content, IdType, Id, ReportType, Dates)
        return intact_url

    # 如果节点不包含'@',直接返回节点的path
    # Balancesheet和MCInfo是没有isDerived
    @staticmethod
    def get_path(values):
        path = None
        if 'IncomeStatement' in values['nodeType']:
            path = "/FinancialReports[@companyId='" + values.get('companyId') \
                   + "']/IncomeStatements/IncomeStatement[@asOf='" + values.get('asOf') + "' and @reportType='" \
                   + values.get('reportType') + "' and @fiscalYearEnd='" + values.get('fiscalYearEnd') \
                   + "' and @numberOfMonth='" + values.get('numberOfMonth') \
                   + "' and @currencyId='" + values.get('currencyId') \
                   + "' and @isDerived='" + values.get('isDerived') \
                   + "']/" \
                   + values['targetNode']
        elif 'BalanceSheet' in values['nodeType']:
            path = "/FinancialReports[@companyId='" + values.get('companyId') \
                   + "']/BalanceSheets/BalanceSheet[@asOf='" + values.get('asOf') + "' and @reportType='" \
                   + values.get('reportType') + "' and @fiscalYearEnd='" + values.get('fiscalYearEnd') \
                   + "' and @numberOfMonth='" + values.get('numberOfMonth') \
                   + "' and @currencyId='" + values.get('currencyId') \
                   + "']/" \
                   + values['targetNode']
        elif 'CashFlow' in values['nodeType']:
            path = "/FinancialReports[@companyId='" + values.get('companyId') \
                   + "']/CashFlows/CashFlow[@asOf='" + values.get('asOf') + "' and @reportType='" \
                   + values.get('reportType') + "' and @fiscalYearEnd='" + values.get('fiscalYearEnd') \
                   + "' and @numberOfMonth='" + values.get('numberOfMonth') + "' and @currencyId='" \
                   + values.get('currencyId') \
                   + "' and @isDerived='" + values.get('isDerived') + "']/" \
                   + values['targetNode']
        elif 'MiscInfo' in values['nodeType']:
            path = "/FinancialReports[@companyId='" + values.get('companyId') \
                   + "']/MiscFinancialData/MiscInfo[@asOf='" + values.get('asOf') + "' and @reportType='" \
                   + values.get('reportType') + "' and @fiscalYearEnd='" + values.get('fiscalYearEnd') \
                   + "' and @numberOfMonth='" + values.get('numberOfMonth') + "' and @currencyId='" \
                   + values.get('currencyId') + "']/" \
                   + values['targetNode']
        return path

    # 如果节点包含'@' 应该返回属性的path
    # Balancesheet 和 MCInfo是没有的isDerived
    @staticmethod
    def get_attr_path(values):
        path = None
        if 'IncomeStatement' in values['nodeType']:
            path = "/FinancialReports[@companyId='" + values.get('companyId') \
                   + "']/IncomeStatements/IncomeStatement[@asOf='" + values.get('asOf') + "' and @reportType='" \
                   + values.get('reportType') + "' and @fiscalYearEnd='" + values.get('fiscalYearEnd') \
                   + "' and @numberOfMonth='" + values.get('numberOfMonth') \
                   + "' and @currencyId='" + values.get('currencyId') \
                   + "' and @isDerived='" + values.get('isDerived') \
                   + "' and " + values.get('targetNode') + "='" \
                   + values.get(values.get('targetNode')) + "']"  # only need get attr
        elif 'BalanceSheet' in values['nodeType']:
            path = "/FinancialReports[@companyId='" + values.get('companyId') \
                   + "']/BalanceSheets/BalanceSheet[@asOf='" + values.get('asOf') + "' and @reportType='" \
                   + values.get('reportType') + "' and @fiscalYearEnd='" + values.get('fiscalYearEnd') \
                   + "' and @numberOfMonth='" + values.get('numberOfMonth') \
                   + "' and @currencyId='" + values.get('currencyId') \
                   + "' and " + values.get('targetNode') + "='" \
                   + values.get(values.get('targetNode')) + "']"  # only need get attr
        elif 'CashFlow' in values['nodeType']:
            path = "/FinancialReports[@companyId='" + values.get('companyId') \
                   + "']/CashFlows/CashFlow[@asOf='" + values.get('asOf') + "' and @reportType='" \
                   + values.get('reportType') + "' and @fiscalYearEnd='" + values.get('fiscalYearEnd') \
                   + "' and @numberOfMonth='" + values.get('numberOfMonth') \
                   + "' and @currencyId='" + values.get('currencyId') \
                   + "' and @isDerived='" + values.get('isDerived') \
                   + "' and " + values.get('targetNode') + "='" \
                   + values.get(values.get('targetNode')) + "']"  # only need get attr
        elif 'MiscInfo' in values['nodeType']:
            path = "/FinancialReports[@companyId='" + values.get('companyId') \
                   + "']/MiscFinancialData/MiscInfo[@asOf='" + values.get('asOf') + "' and @reportType='" \
                   + values.get('reportType') + "' and @fiscalYearEnd='" + values.get('fiscalYearEnd') \
                   + "' and @numberOfMonth='" + values.get('numberOfMonth') \
                   + "' and @currencyId='" + values.get('currencyId') \
                   + "' and " + values.get('targetNode') + "='" \
                   + values.get(values.get('targetNode')) + "']"  # only need get attr
        return path